person:
  age: 11
  name: 张三
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
  #resources:
    #static-locations: classpath:/static/example2/,classpath:/static/example/,classpath:/static/
  #mvc:
    #static-path-pattern: /static/*.html
    data-username:

  #Controller return --->>配置式替代 / & .  /suceess.html --> suceess  注意:返回注解 is Controller  no RestController -- no ResposeBody
  mvc:
    view:
      prefix: /
      suffix: .html

# load Mapper.xml resource Path
mybatis:
  mapper-locations: classpath:mappers/*.xml   #
  #type-aliases-package: com.example.*.*  Entity 实体类位置扫描   不配置的情况下也可以扫描到实体类? ? ? smark 后续解决 原因(自己配置过注解扫描)-->>@MapperScan(value = "com.example.*.*")
# set default parameter
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100

 #Mysql CRUD default console print/show
logging:
  level:
    com.example: DEBUG



